version: '3.9'

services:
  client:
    build: 
      context: ./GraphQL_Frontend
      dockerfile: ./Dockerfile
    ports:
      - 4173:4173
    environment:
      - VITE_BACKEND_URL=http://api
  api:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      # - DB_URL=mongodb://db/vidly
      DB_URL: mongodb://db/vidly
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db #maps it outside
volumes:
  vidly: